version: '3.8'

services:
  app:
    container_name: instagram-x-integration
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env  # Load environment variables
    restart: always  # Automatically restart on failure
